spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 778903
    url: jdbc:mysql://123.206.113.139/CRM?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
  thymeleaf:
    cache: false
    check-template: false
    mode: LEGACYHTML5
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.fourzeroeight.crm.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8080

com:
  sxito:
    custom:
      windows-path: d:/sxito
      linux-path: /home/robinson/Documents/test/sxito
      keys: fourzeroeight